### ISSUE TITLE
Any API documentation?

### ISSUE THREAD

**Issue by kstan79** [apmuthu/phpMyOLAP#1]
I want to create a data visualization front end with PHP. Seems like phpmyolap may be able to help. Is there any documentation for me to refer?
I'm won't need any GUI component; what I need is the API to connect database, generate cube, filter, aggregate data into array/json form...

**Comment by apmuthu** [comment]
- The only official documentation available is the [pdf](https://raw.githubusercontent.com/apmuthu/phpMyOLAP/master/phpMyOLAP.pdf) file in it.
- The [config.php](https://github.com/apmuthu/phpMyOLAP/blob/master/phpMyOLAP/config.php) file can be appropriately filled in.
- The [schema xml](https://github.com/apmuthu/phpMyOLAP/blob/master/phpMyOLAP/schema/FoodMart2.xml) files can be prepared as desired for your database tables / views.
- You can make a REST API for it using any of the SOAP projects and incorporate it here for your application.

**Comment by kstan79** [comment]
its ok, tq. i'd created another olap project in php. https://github.com/SIMITGROUP/olapengine/wiki
still need few more days.
