### ISSUE TITLE
Null warning

### ISSUE THREAD

**Issue by cynthialow** [apmuthu/phpMyOLAP#2]
Hi, I'm new to phpMyOLAP. May I know why are they all null values? Where could the problem be at?

![image](https://user-images.githubusercontent.com/47199096/69474305-8013fc80-0dfa-11ea-8957-9cda62395e5d.png)

**Comment by apmuthu** [comment]
You have a mysql user permissions issue. Since you are using a later version of PHP (state version of PHP, MySQL, etc), it does not degrade gracefully and hence the errors shown. It is also possible you have not populated the sqls necessary for the application.

**Comment by ming0520** [comment]
i also face the same problem, but i did update to latest xampp, may i know more about the setting and what should i lookup?
